// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: proto/gravity/v1/gravity.proto

package gravityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GravityService_SubmitTask_FullMethodName     = "/gravity.v1.GravityService/SubmitTask"
	GravityService_SubmitVote_FullMethodName     = "/gravity.v1.GravityService/SubmitVote"
	GravityService_SubmitProposal_FullMethodName = "/gravity.v1.GravityService/SubmitProposal"
)

// GravityServiceClient is the client API for GravityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GravityServiceClient interface {
	SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error)
	SubmitVote(ctx context.Context, in *SubmitVoteRequest, opts ...grpc.CallOption) (*SubmitVoteResponse, error)
	SubmitProposal(ctx context.Context, in *SubmitProposalRequest, opts ...grpc.CallOption) (*SubmitProposalResponse, error)
}

type gravityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGravityServiceClient(cc grpc.ClientConnInterface) GravityServiceClient {
	return &gravityServiceClient{cc}
}

func (c *gravityServiceClient) SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskResponse)
	err := c.cc.Invoke(ctx, GravityService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravityServiceClient) SubmitVote(ctx context.Context, in *SubmitVoteRequest, opts ...grpc.CallOption) (*SubmitVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitVoteResponse)
	err := c.cc.Invoke(ctx, GravityService_SubmitVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravityServiceClient) SubmitProposal(ctx context.Context, in *SubmitProposalRequest, opts ...grpc.CallOption) (*SubmitProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProposalResponse)
	err := c.cc.Invoke(ctx, GravityService_SubmitProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GravityServiceServer is the server API for GravityService service.
// All implementations must embed UnimplementedGravityServiceServer
// for forward compatibility.
type GravityServiceServer interface {
	SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error)
	SubmitVote(context.Context, *SubmitVoteRequest) (*SubmitVoteResponse, error)
	SubmitProposal(context.Context, *SubmitProposalRequest) (*SubmitProposalResponse, error)
	mustEmbedUnimplementedGravityServiceServer()
}

// UnimplementedGravityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGravityServiceServer struct{}

func (UnimplementedGravityServiceServer) SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedGravityServiceServer) SubmitVote(context.Context, *SubmitVoteRequest) (*SubmitVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitVote not implemented")
}
func (UnimplementedGravityServiceServer) SubmitProposal(context.Context, *SubmitProposalRequest) (*SubmitProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitProposal not implemented")
}
func (UnimplementedGravityServiceServer) mustEmbedUnimplementedGravityServiceServer() {}
func (UnimplementedGravityServiceServer) testEmbeddedByValue()                        {}

// UnsafeGravityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GravityServiceServer will
// result in compilation errors.
type UnsafeGravityServiceServer interface {
	mustEmbedUnimplementedGravityServiceServer()
}

func RegisterGravityServiceServer(s grpc.ServiceRegistrar, srv GravityServiceServer) {
	// If the following call panics, it indicates UnimplementedGravityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GravityService_ServiceDesc, srv)
}

func _GravityService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravityServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravityService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravityServiceServer).SubmitTask(ctx, req.(*SubmitTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GravityService_SubmitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravityServiceServer).SubmitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravityService_SubmitVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravityServiceServer).SubmitVote(ctx, req.(*SubmitVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GravityService_SubmitProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravityServiceServer).SubmitProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GravityService_SubmitProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravityServiceServer).SubmitProposal(ctx, req.(*SubmitProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GravityService_ServiceDesc is the grpc.ServiceDesc for GravityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GravityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.v1.GravityService",
	HandlerType: (*GravityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _GravityService_SubmitTask_Handler,
		},
		{
			MethodName: "SubmitVote",
			Handler:    _GravityService_SubmitVote_Handler,
		},
		{
			MethodName: "SubmitProposal",
			Handler:    _GravityService_SubmitProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gravity/v1/gravity.proto",
}
