// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/gravity/v1/gravity.proto

package gravityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Requester     string                 `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"` // Optional, defaults to "api-user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitTaskRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SubmitVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoteRequest) Reset() {
	*x = SubmitVoteRequest{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteRequest) ProtoMessage() {}

func (x *SubmitVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteRequest.ProtoReflect.Descriptor instead.
func (*SubmitVoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitVoteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitVoteRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubmitVoteRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SubmitVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoteResponse) Reset() {
	*x = SubmitVoteResponse{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoteResponse) ProtoMessage() {}

func (x *SubmitVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoteResponse.ProtoReflect.Descriptor instead.
func (*SubmitVoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitVoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitVoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubmitAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAnswerRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gravity_v1_gravity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_gravity_v1_gravity_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitAnswerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitAnswerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gravity_v1_gravity_proto protoreflect.FileDescriptor

const file_proto_gravity_v1_gravity_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gravity/v1/gravity.proto\x12\n" +
	"gravity.v1\"K\n" +
	"\x11SubmitTaskRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\trequester\x18\x02 \x01(\tR\trequester\"-\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"c\n" +
	"\x11SubmitVoteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\"H\n" +
	"\x12SubmitVoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"J\n" +
	"\x14SubmitAnswerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfd\x01\n" +
	"\x0eGravityService\x12K\n" +
	"\n" +
	"SubmitTask\x12\x1d.gravity.v1.SubmitTaskRequest\x1a\x1e.gravity.v1.SubmitTaskResponse\x12K\n" +
	"\n" +
	"SubmitVote\x12\x1d.gravity.v1.SubmitVoteRequest\x1a\x1e.gravity.v1.SubmitVoteResponse\x12Q\n" +
	"\fSubmitAnswer\x12\x1f.gravity.v1.SubmitAnswerRequest\x1a .gravity.v1.SubmitAnswerResponseB=Z;github.com/dhiaayachi/gravity-ai/proto/gravity/v1;gravityv1b\x06proto3"

var (
	file_proto_gravity_v1_gravity_proto_rawDescOnce sync.Once
	file_proto_gravity_v1_gravity_proto_rawDescData []byte
)

func file_proto_gravity_v1_gravity_proto_rawDescGZIP() []byte {
	file_proto_gravity_v1_gravity_proto_rawDescOnce.Do(func() {
		file_proto_gravity_v1_gravity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gravity_v1_gravity_proto_rawDesc), len(file_proto_gravity_v1_gravity_proto_rawDesc)))
	})
	return file_proto_gravity_v1_gravity_proto_rawDescData
}

var file_proto_gravity_v1_gravity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_gravity_v1_gravity_proto_goTypes = []any{
	(*SubmitTaskRequest)(nil),    // 0: gravity.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),   // 1: gravity.v1.SubmitTaskResponse
	(*SubmitVoteRequest)(nil),    // 2: gravity.v1.SubmitVoteRequest
	(*SubmitVoteResponse)(nil),   // 3: gravity.v1.SubmitVoteResponse
	(*SubmitAnswerRequest)(nil),  // 4: gravity.v1.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil), // 5: gravity.v1.SubmitAnswerResponse
}
var file_proto_gravity_v1_gravity_proto_depIdxs = []int32{
	0, // 0: gravity.v1.GravityService.SubmitTask:input_type -> gravity.v1.SubmitTaskRequest
	2, // 1: gravity.v1.GravityService.SubmitVote:input_type -> gravity.v1.SubmitVoteRequest
	4, // 2: gravity.v1.GravityService.SubmitAnswer:input_type -> gravity.v1.SubmitAnswerRequest
	1, // 3: gravity.v1.GravityService.SubmitTask:output_type -> gravity.v1.SubmitTaskResponse
	3, // 4: gravity.v1.GravityService.SubmitVote:output_type -> gravity.v1.SubmitVoteResponse
	5, // 5: gravity.v1.GravityService.SubmitAnswer:output_type -> gravity.v1.SubmitAnswerResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gravity_v1_gravity_proto_init() }
func file_proto_gravity_v1_gravity_proto_init() {
	if File_proto_gravity_v1_gravity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gravity_v1_gravity_proto_rawDesc), len(file_proto_gravity_v1_gravity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gravity_v1_gravity_proto_goTypes,
		DependencyIndexes: file_proto_gravity_v1_gravity_proto_depIdxs,
		MessageInfos:      file_proto_gravity_v1_gravity_proto_msgTypes,
	}.Build()
	File_proto_gravity_v1_gravity_proto = out.File
	file_proto_gravity_v1_gravity_proto_goTypes = nil
	file_proto_gravity_v1_gravity_proto_depIdxs = nil
}
